### ISSUE TITLE
ReadWrite/ReadOnly/WriteOnly should allow additional range types

### ISSUE THREAD

**Issue by phausler** [apple/swift-mmio#28]
It would often be useful to express bit fields as closed ranges or other such range types:

`
@ReadWrite(22...22, as: Bool.self)
var booleanLikeThing: BooleanLikeThing
`

or the remaining bits in a register layout:
`
@ReadOnly(16..., as: UInt16.self) 
var remainingBits: RemainingBits
`

**Comment by rauhul** [comment]
I have this mostly functional, but I'm trying to figure out if I can support `...` (unbound range) without needing an additional overload which could hurt compiler performance

**Comment by rauhul** [comment]
Got it working with help from @ahoppen (thank you!)
