### ISSUE TITLE
RawRepresentable should have a conditional extension when conforming to BitFieldProjectable

### ISSUE THREAD

**Issue by phausler** [apple/swift-mmio#32]
```swift
extension RawRepresentable where Self: BitFieldProjectable, RawValue: FixedWidthInteger {
  public init<Storage>(storage: Storage) where Storage: FixedWidthInteger & UnsignedInteger {
    self.init(rawValue: RawValue(storage))!
  }

  public func storage<Storage>(`_`: Storage.Type) -> Storage where Storage: FixedWidthInteger & UnsignedInteger {
    Storage(rawValue)
  }
}
```

This allows enumerations with raw value types to be easily emitted as bit field projections.

```swift
        public enum UMSEL0Values: UInt8, BitFieldProjectable {
          case asynchronous`_`usart = 0x0
          case synchronous`_`usart = 0x1
          case master`_`spi = 0x3
          
          public static var bitWidth: Int { 2 }
        }
```

**Comment by SamHastings1066** [comment]
Unless there are any objections, I'll open a draft PR request adding in the proposed extension to Sources/MMIO/BitFieldProjectable.swift, and I'll create some unit tests to validate that it's functioning as expected.

**Comment by rauhul** [comment]
> Unless there are any objections, I'll open a draft PR request adding in the proposed extension to Sources/MMIO/BitFieldProjectable.swift, and I'll create some unit tests to validate that it's functioning as expected.

Fantastic, thanks for taking this. Ping me here or in a PR if you have questions.

**Comment by SamHastings1066** [comment]
Hi there @rauhul, have you had a chance to take a look at my draft PR? Am I on the right track?

**Comment by rauhul** [comment]
@SamHastings1066 Apologies this fell off my todo list due to some demo prep!
