### ISSUE TITLE
It would be useful to have common bit sizes of unsigned integers for BitFieldProjectables

### ISSUE THREAD

**Issue by phausler** [apple/swift-mmio#41]
`UInt8`, `UInt16`, `UInt32`, and `UInt64` are common field member types (when not enumerations or option sets).

```swift
extension UInt8: BitFieldProjectable {
  public static var bitWidth: Int { 8 }

  public init<Storage>(storage: Storage)
  where Storage: FixedWidthInteger & UnsignedInteger {
    self.init(storage)
  }

  public func storage<Storage>(_: Storage.Type) -> Storage
  where Storage: FixedWidthInteger & UnsignedInteger {
    Storage(self)
  }
}
```

**Comment by rauhul** [comment]
yep this makes sense, ideally we could represent this as:

```swift
extension<T> T: BitFieldProjectable where T: FixedWidthInteger {
  // public static var bitWidth: Int -- Already a requirement of FixedWidthInteger  
  public init<Storage>(storage: Storage) ...
  public func storage<Storage>(_: Storage.Type) -> Storage ...
}
```

**Comment by phausler** [comment]
iirc the `extension<T>` isn't valid syntax yet.

**Comment by rauhul** [comment]
Yeah this isn't something we can write yet, instead we will need to write out conformances for `[U]Int{8,16,32,64}`

**Comment by phausler** [comment]
that seems like something that could be added earlier for the utility and then later generalized when the language grows that feature.

**Comment by rauhul** [comment]
Absolutely, I'm not suggesting this wait for `extension<T>` to exist.
