### ISSUE TITLE
MMIOVolatile can be refactored into a systemLibrary

### ISSUE THREAD

**Issue by phausler** [apple/swift-mmio#50]
The MMIOVolatile target has an empty c file which can be removed (reducing complexity of linking) and made into a `systemLibrary` that defines a header + module.modulemap.

**Comment by rauhul** [comment]
Do you have an example?

**Comment by phausler** [comment]
so in the `Package.swift` change
`    .target(name: "MMIOVolatile"),`
to
`    .systemLibrary(name: "MMIOVolatile"),`

And then move the header to the top level of that directory and add a module.modulemap:

```
module MMIOVolatile {
    header "MMIOVolatile.h"
    export *
}
```

**Comment by rauhul** [comment]
Wow I did not realize this was an SPM feature 😮

**Comment by rauhul** [comment]
I attempted to make this change on branch `system-library` but it breaks the FileCheck tests in an unexpected manner:
```
Command 'swiftc -emit-ir Tests/MMIOFileCheckTests/Tests/TestRegisterModifyRawSet.swift -o .build/FileCheck/TestRegisterModifyRawSet.swift.ll -target arm64-apple-macosx14.0 -O -I .build/FileCheck/release -load-plugin-executable .build/FileCheck/release/MMIOMacros#MMIOMacros -parse-as-library' exited with code '1': error: missing required module 'MMIOVolatile'
```

**Comment by phausler** [comment]
it may need additional flags to get FileCheck to work
