### ISSUE TITLE
Rename RegisterBank to RegisterBlock or RegisterCluster

### ISSUE THREAD

**Issue by ugurkoltuk** [apple/swift-mmio#67]
Blocks or clusters of registers in SwiftMMIO are called "RegisterBank", which is a little bit confusing because it might be confused with "Register Banking" in various ARM specs (e.g. in https://www.cl.cam.ac.uk/research/srg/han/ACS-P35/zynq/arm_gic_architecture_specification.pdf "Register banking refers to providing multiple copies of a register at the same address.")

It seems ip-xact calls this thing registerFile (https://www.accellera.org/images/downloads/standards/ip-xact/IP-XACT_User_Guide_2018-02-16.pdf), though that can be confused with registers in the CPU (https://en.wikipedia.org/wiki/Register_file)

So let's rename RegisterBank to either RegisterBlock or RegisterCluster. I think either of them are less ambiguous

**Comment by fumoboy007** [comment]
Are “register block” or “register cluster” terms-of-art or just general terms? If they are just general terms, then perhaps we could use “register group”, which seems slightly simpler to me (just my opinion).

**Comment by ugurkoltuk** [comment]
There doesn't seem to be a globally agreed-upon term for this, and some specifications just don't name the thing, but in a few specs I have seen the use "register block" to refer to a set of contiguous registers that are related to each other. (e.g. they control the same peripheral)

**Comment by rauhul** [comment]
Cluster is likely the name to use here, I agree that Bank isn't quite right. It's annoying that the IEEE IP-XACT spec uses RegisterFile which is quite a bad name. 

Arm uses "cluster" in a couple other places for this concept.

**Comment by rauhul** [comment]
After consulting with a couple of other folks inside Apple, I think "block" is the best name here, though "group" was strongly considered.

**Comment by rauhul** [comment]
Moved this to 0.1.0 as it is a source breaking change
